### PR TITLE
should work, report to me any issues

### PR DESCRIPTION
**Pull request by jean1398reborn**
created an extra file which adds slash commands to stw daily

(also theres just a bunch of commands i've put aside as i dont really see the use of them)

### CODE REVIEW

**Comment by jean1398reborn** [comment]
ok new version should be better

**Comment by jean1398reborn** [comment]
hi

**Comment by jean1398reborn** [comment]
hi

**Comment by jean1398reborn** [comment]
hi

**Comment by jean1398reborn** [comment]
ew pull requests

**Comment by dippyshere** [comment]
thank you for the high quality pull request. your changes are currently under review and will be merged sometime this week. 

:) thanks

**Comment by jean1398reborn** [comment]
wait im not ready yet

**Comment by dippyshere** [comment]
too late ive already merged it lmao. im gonna push it to stw daily

**Comment by jean1398reborn** [comment]
no serriously

**Pull request closed without merging**
